services:
  ai-recommendation-system:
    container_name: ai-recommendation-system
    dns: 
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-recommendation-system
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - REGION=${REGION}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE}
      - S3_BUCKET=${S3_BUCKET}
      - EXPORT_PREFIX=${EXPORT_PREFIX}
    env_file:
      - .env 
    working_dir: /app
    command: uvicorn api.recommend:app --host 0.0.0.0 --port 8080 --reload
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./streamlit:/app/streamlit
    working_dir: /app/streamlit
    command: streamlit run app.py --server.address 0.0.0.0 --server.port 8501
    ports:
      - "8501:8501"
    depends_on:
      - ai-recommendation-system
    networks:
      - app-network

networks:
  app-network:
    driver: bridge